Added validateaddress endpoint
SatoshiPortal/cyphernode pull request #233
Opened 2021-11-15 21:51 UTC by Kexkey

Added `validateaddress` endpoint.  Delegates to Bitcoin Core's `validateaddress`.

2021-11-17 08:31 UTC, schulterklopfer commented on doc/openapi/v0/cyphernode-api.yaml
> +                # TODO: describe response
Please describe response ;)

2021-11-17 08:32 UTC, schulterklopfer requested changes
see comment in openapi document

2021-11-18 16:23 UTC, Kexkey commented on doc/openapi/v0/cyphernode-api.yaml
> +                # TODO: describe response
Done

2021-11-18 18:00 UTC, schulterklopfer commented on doc/openapi/v0/cyphernode-api.yaml
> +                # TODO: describe response
nice :D

2021-11-18 18:01 UTC, schulterklopfer approved these changes
lgtm

2021-11-18 18:03 UTC, schulterklopfer approved these changes

2021-11-18 20:37 UTC, merged